### ISSUE TITLE
Maximum call stack size exceeded upon upgrading to testcafe 1.1.1

### ISSUE THREAD

**Issue by benaduggan** [DevExpress/testcafe-react-selectors#141] opened 2019-05-10 15:37 UTC
I recently upgraded our project to use a newer version of testcafe, and the `getReact()` call is now bombing out with a Call Stack exceeded error message. Any idea what might have cause this problem?

**Comment by AlexKamaev** [comment] 2019-05-13 08:46
It's difficult to determine the cause of the issue based only on your description. We would really appreciate it if you provide a sample working project (or public url to your project). Please also specify your previous TestCafe version and your OS/Browser information

**Comment by benaduggan** [comment] 2019-05-13 13:17
I'm not sure when I'll have time to set up a test project since our product is not OSS, but in the meantime I did figure out the test ran in 1.1.0, but not any version after. I'm on ubuntu 18.04 and ran with chrome 74, chrome:headless, and firefox 66 which all had the same issue. Is there any other browser/os information that y'all would like? I'll try to get back with a test project soon.

**Comment by AlexKamaev** [comment] 2019-05-13 14:00
Thank you for your cooperation. This information is enough. We are looking forward to your project to research it.

**Comment by bhoogter** [comment] 2019-07-16 19:32
We are also experiencing this issue with ChromeDriver 75 and TestCafe 1.3.2.

Reverting TestCafe via npm to 1.1.0 makes the tests pass.

The issue is very intermittent.  We duplicated a one-line test some 20 times or so and kept re-running it.  The test would fail in the beforeEach() in a different spot on a random test number, usually within 5-6 tests, but sometimes as many as ten.  It would fail for about 3-4 tests, and then sometimes start working again.  Suppressing javascript errors was not sufficient, since it caused the page to fail loading...

The before each is extremely simple (where dataQa() is a custom Selector()).....
>    .beforeEach(async t => {
>        await t
>            .useRole(userAdmin)
>            .navigateTo(url)
>            .click(dataQa('nav-drivers', 'li'))

And the test is...
> function item() {return Selector('[data-qa=health-overview-heading]') }
> test('Test #28', async t => { await t.expect(item().exists).ok()})

**Comment by miherlosev** [comment] 2019-07-17 12:58
Hi @benaduggan 

Could you please run TestCafe in [development mode](https://devexpress.github.io/testcafe/documentation/using-testcafe/configuration-file.html#developmentmode) and provide us with the error stack again?

**Comment by bhoogter** [comment] 2019-07-17 13:38
Sure.  New to TestCafe here, so forgive the ignorance.

```
      JavaScript error details:
      RangeError: Maximum call stack size exceeded
          at String.replace (<anonymous>)
          at removeSourceMap (http://xxx.xx.x.o:62494/hammerhead.js:26472:21)
          at preprocess (http://xxx.xx.x.o:62494/hammerhead.js:26464:24)
          at processScript (http://xxx.xx.x.o:62494/hammerhead.js:26573:27)
          at value (http://xxx.xx.x.o:62494/hammerhead.js:9886:88)
          at Object.<anonymous> (http://localhost:8080/app.js:753:7)
          at __webpack_require__ (http://localhost:8080/app.js:654:38)
          at fn (http://localhost:8080/app.js:87:20)
          at eval (webpack-internal:///693:23:26)
          at Object.<anonymous> (http://localhost:8080/app.js:4959:1)

      Browser: Chrome 75.0.3770 / Mac OS X 10.14.5

         10 |
         11 |fixture('Health Landing Page')
         12 |    .beforeEach(async t => {
         13 |        await t
         14 |            .useRole(fcsAdmin)
       > 15 |            .navigateTo(`${url}`)
         16 |        await selectCustomer(t, 'DriverCustomer')
         17 |        await t
         18 |            .click(Selector(dataQa('nav-health', 'li')))
         19 |    });
         20 |

         at navigateTo (.../src/tests/health/health-page.js:15:14)
         at fixture.beforeEach (.../src/tests/health/health-page.js:11:1)
         at <anonymous> (.../node_modules/testcafe/src/api/wrap-test-function.js:17:28)
         at TestRun._executeTestFn (.../node_modules/testcafe/src/test-run/index.js:263:19)
         at TestRun._runBeforeHook (.../node_modules/testcafe/src/test-run/index.js:283:31)
         at TestRun.start (.../node_modules/testcafe/src/test-run/index.js:311:24)
```

**Comment by miherlosev** [comment] 2019-07-17 14:57
I've found the [bug](https://github.com/DevExpress/testcafe-hammerhead/issues/2082) in the `testcafe-hammerhead` module. Track it be informed about our progress.

Also, I will close this issue because the problem is not related to `testcafe-react-selectors` module.

**Closed** 2019-07-17 15:07 UTC
Labels: STATE: Need clarification
