### ISSUE TITLE
Testcafe-react-selector throws react version error

### ISSUE THREAD

**Issue by vvedachalam** [DevExpress/testcafe-react-selectors#80] opened 2018-02-21 12:28 UTC
I am getting the below error when I use react-selector in my project:

 Error: { type: 'uncaughtErrorInClientFunctionCode',
       isTestCafeError: true,
       callsite:
        CallsiteRecord {
          filename: 'C:\\_git\\Proj\\fold\\app\\features\\step_definitions\\mif.js',
          lineNum: 19,
          callsiteFrameIdx: 5,
          stackFrames:
           [ CallSite {},
             CallSite {},
             CallSite {},
             CallSite {},
             CallSite {},
             CallSite {} ],
          isV8Frames: true },
       errMsg: 'Error: testcafe-react-selectors supports React version 15.x and newer',
       instantiationCallsiteName: 'with' }

I am using react version 15.5.4.

**Comment by kirovboris** [comment] 2018-02-22 11:30
Hi @vvedachalam,

Unfortunately, I can't reproduce this issue.
The following details could help us to find the problem:
- testcafe version
- browser version
- test code
- link to your website or minimal working example

**Comment by leegee** [comment] 2018-02-22 11:40
`Error: testcafe-react-selectors supports React version 15.x and newer`

`yarn list react`
...`react@15.6.2`

Latest Testcafe with headless Chrome, code came straight from the example page at testcafe website.

**Comment by kirovboris** [comment] 2018-02-22 11:49
Thank you, @leegee. I'll investigate it.

**Comment by leegee** [comment] 2018-02-22 11:49
Please let me know if I can help, this mod looks really useful!

**Comment by kirovboris** [comment] 2018-02-26 07:40
@leegee, could you please provide the simplified code of the root component? I see what causes this bug from your example, but i can't reproduce it. Also please check this issue with `testcafe-react-selctors@1.0.4`.

**Comment by leegee** [comment] 2018-02-27 13:12
Not even the simplified, I'm sorry. I can answer specific questions, though, if it helps....

Not my code base, sorry: terms of contract.

**Comment by kirovboris** [comment] 2018-03-14 08:06
@leegee, I've just published `testcafe-react-selectors@1.0.6`. Could you please check if this issue still reproduces?

**Comment by leegee** [comment] 2018-03-14 08:19
Thanks, but I'm afraid not — had to switch library :(

**Comment by kirovboris** [comment] 2018-03-19 06:33
It was fixed in `testcafe-react-selectors@1.0.6`, so I close this issue. Please let me know if the problem still occurs.

**Closed by kirovboris** 2018-03-19 06:33 UTC
Labels: bug
